### ISSUE TITLE
Is it possible to load the calendar with events / dates ?

### ISSUE THREAD

**Issue by slishnevsky** [dalelotts/angularjs-bootstrap-datetimepicker#1]
Lets say I receive my events from my Google Calendar as an array of items that contain start date time, and date time.

Is it possible to display these dates in the Calendar? 
I tried to set a single Date field to ng-model='vm.today', it paints the cell in blue.
I tried to set an array of Dates to ng-model='vm.dates', it doesn't display anything.
Is it capable of displaying multiple dates on the Calendar UI?

Thanks.

**Comment by dalelotts** [comment]
Sorry, this is not possible with one date-picker

**Comment by slishnevsky** [comment]
Thanks
