### ISSUE TITLE
Dependencies are wrong

### ISSUE THREAD

**Issue by AndyVulhop** [dalelotts/angularjs-bootstrap-datetimepicker#13]
The readme said this is dependent on angularjs 1.4.x and moment.js 2.8.3+, but the latest release is leaning on "angular": "^1.6.3", "moment": "^2.18.1", per the package.json in the latest release here: https://github.com/dalelotts/angularjs-bootstrap-datetimepicker/releases

**Comment by dalelotts** [comment]
Sorry for the delay, just seeing this now. I will update the readme shortly

**Comment by dalelotts** [comment]
Done
