### ISSUE TITLE
The example that in the officaial document is not working

### ISSUE THREAD

**Issue by ToView** [dalelotts/angularjs-bootstrap-datetimepicker#2]
I tried to find an example in the official document, but found that the official example is not working properly

**Comment by dalelotts** [comment]
There is more than one example in the docs. Can you tell me which one you tried and the error that you saw (if any error)?

**Comment by dalelotts** [comment]
The simplest example is this one - https://github.com/dalelotts/angularjs-bootstrap-datetimepicker#usage - should I move it to the top of the page?

**Comment by ToView** [comment]
![image](https://user-images.githubusercontent.com/23398131/37806600-db32edd4-2e7b-11e8-872d-98e465d973a1.png)

I browse this way: https://dalelotts.github.io/angularjs-bootstrap-datetimepicker/

**Comment by dalelotts** [comment]
Hmm, that's surprising, I just checked it using Chrome, Safari, and Firefox and it works. Is there anything in the console?  What browser are you using?

**Comment by ToView** [comment]
![image](https://user-images.githubusercontent.com/23398131/37826895-3a57a2c4-2ed0-11e8-8005-d0f6c29398f9.png)
I use chrome. I think it should be a problem with my network.

**Comment by dalelotts** [comment]
I agree, it looks like your network is the issue. I've seen that before on certain guest networks but I am not sure what settings cause it.
