### ISSUE TITLE
I need minutestep to be updated dynamically, how can be acheived

### ISSUE THREAD

**Issue by rssaranece94** [dalelotts/angularjs-bootstrap-datetimepicker#8]
<datetimepicker data-ng-model="BreakTime2" data-on-set-time="onTimeSet(newDate, oldDate)"data-datetimepicker-config="{ startView: 'hour', minuteStep: {{minuteStepmodal}}, dropdownSelector: '.dropdown-toggle' }"></datetimepicker>

**Comment by rssaranece94** [comment]
Thanks, I fixed in before render function.

**Comment by dalelotts** [comment]
I'm not sure what you did in the before-render callback, but you might consider using [`configureOn`](https://github.com/dalelotts/angularjs-bootstrap-datetimepicker#configureon) since it is designed for this purpose.

**Comment by niketpatil** [comment]
@dalelotts Can you give any example? How to use configueOn option??
